name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"
  schedule:
    - cron: '0 0 * * *'

jobs:
  qa:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.17.0
    steps:
      - uses: actions/checkout@v1
      - name: Install shards
        run: shards install --ignore-crystal-version
      - name: QA checks
        run: make qa
  specs:
    strategy:
      fail-fast: false
      matrix:
        crystal:
          - latest
          - nightly
          - 1.15.0
          - 1.16.0
          - 1.17.0
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:${{ matrix.crystal }}
    steps:
    - uses: actions/checkout@v2
    - name: Install shards
      run: shards install --ignore-crystal-version --skip-postinstall --skip-executables
    - name: Run tests
      run: make tests
