name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: "*"

jobs:
  qa:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.35.1
    steps:
      - uses: actions/checkout@v1
      - name: Install shards
        run: shards install --ignore-crystal-version
      - name: QA checks
        run: make qa
  specs:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.35.1
    steps:
    - uses: actions/checkout@v2
    - name: Install shards
      run: shards install --ignore-crystal-version
    - name: Cache Crystal
      uses: actions/cache@v1
      with:
        path: ~/.cache/crystal
        key: ${{ runner.os }}-crystal
    - name: Run tests
      run: make tests
